### ISSUE TITLE
full stack nano degree update

### ISSUE THREAD

**Issue by ahmedvip2008** [mikesprague/udacity-nanodegrees#10]
there is a new version released 

you can find it here 
https://files.slack.com/files-pri/T0JJ5DTBL-F55R1F0JD/download/syllabus-fullstackwebdeveloperndv4.0.pdf

or here
https://udacity-nanodegrees.typeform.com/to/uMXJLZ

**Comment by mikesprague** [comment]
Thanks, @ahmedvip2008! Unfortunately, those are only currently available if you're already enrolled in that ND. 

In addition, the new courses are not linked to (so I also can not link to them) and I am unable to verify the courses are free.

If/when these go live on the main Udactiy site (and the individual courses are offered free) I'll happily update the list here!

**Comment by mikesprague** [comment]
@ahmedvip2008 These have now been added thanks to pull request #12
