### ISSUE TITLE
Updated links for new courses for Full Stack ND

### ISSUE THREAD

**Issue by nikhilbansal97** [mikesprague/udacity-nanodegrees#11]
Kindly Add the below courses as they were included in the Full Stack ND 4.0 update :

Version Control with Git (ud123) — instructor Richard Kalehoff
https://www.udacity.com/course/version-control-with-git--ud123

GitHub and Collaboration (ud456) — instructor Richard Kalehoff
https://www.udacity.com/course/github-collaboration--ud456

Shell Workshop (ud206) — instructor Karl Krueger
https://www.udacity.com/course/shell-workshop--ud206

HTTP & Web Servers (ud303) — instructor Karl Krueger
https://www.udacity.com/course/http-web-servers--ud303

Designing RESTful APIs (ud388) — instructor Lorenzo Brown
https://www.udacity.com/course/designing-restful-apis--ud388

**Comment by tomicakorac** [comment]
@nikhilbansal97 why not add it yourself and send a pull request?

**Comment by aviral19** [comment]
I have made a pull request regarding this issue.

**Comment by mikesprague** [comment]
Was also reported in issue #10 but links were never provided
