### ISSUE TITLE
Digital Marketing Nanodegree

### ISSUE THREAD

**Issue by lastnoob** [mikesprague/udacity-nanodegrees#13]
The latest nanodegree of Udacity, the Digital Marketing is not listed. I couldn't find the related courses on the Udacity catalog, but maybe you know better than me.

**Comment by mikesprague** [comment]
Thanks for the heads up @lastnoob. I have no affiliation with Udacity, nor do I have a membership to any of their ND programs. 

From the main README:
>NOTE: Only Nanodegree programs with their curricula listed on the Udacity website are part of this list.

That said, I do check occasionally for new listings and gladly take pull requests if/when they add something that I have yet to. Thanks!
