### ISSUE TITLE
is the udacity offer still available?

### ISSUE THREAD

**Issue by c-shankar** [mikesprague/udacity-nanodegrees#20]
I dont find udacity offer listed in the Education section of github

**Comment by nimitbhargava** [comment]
GitHub Education Pack no longer provides 1 month free access to Udacity Nanodegree. @c-shankar

**Comment by mikesprague** [comment]
Just a reminder, I am not affiliated with GitHub or Udacity so I will not normally have answers to these types of questions. Thanks @nimitbhargava for answering!
