### ISSUE TITLE
Can you add the new nanodegrees?

### ISSUE THREAD

**Issue by sntdevco** [mikesprague/udacity-nanodegrees#24]
Can you please add the courses for the new nanodegrees:
1. AI
2. Become a VR Developer
3. Self-driving car nanodegree
4. Deep Learning nanodegree

Thanks in advance!

**Comment by aviral19** [comment]
Whatever courses added here are open for all by Udacity.
New nano-degrees, especially the ones you have mentioned are only available to people who pay for them.
The content is restricted only to those who attend the nanodegrees.
