### ISSUE TITLE
deep learning nonedegree

### ISSUE THREAD

**Issue by engmagdy87** [mikesprague/udacity-nanodegrees#30]
hello
thx for ur efforts
can u add deep learning nanodegree ?

**Comment by mikesprague** [comment]
None of the new nanodegrees list their courses publicly which means there's nothing to add and this request doesn't meet the criteria listed on the readme:

- Nanodegree lists syllabus on it's public-facing (non-logged in) page
- Links to each course in the syllabus are available on the public-facing Nanodegree page
- Individual courses are available to take for free via their public facing course page

Closing. Thanks.
