### ISSUE TITLE
Nanodegrees I would like to see

### ISSUE THREAD

**Issue by Inventrohyder** [mikesprague/udacity-nanodegrees#33]
Could we get to see:
1) Self driving car engineer
2) Virtual reality nanodegree
3) Other nanodegrees like react, flying car, intro to programming etc

**Comment by mikesprague** [comment]
Closing as invalid. Please see the README, particularly:

> All of the Nanodegrees programs listed here meet the following criteria:
> - Nanodegree lists syllabus on it's public-facing (non-logged in) page
> - Links to each course in the syllabus are available on the public-facing Nanodegree page
> - Individual courses are available to take for free via their public facing course page
