### ISSUE TITLE
Update To Full Stack Nanodegree Curriculum

### ISSUE THREAD

**Issue by akhilome** [mikesprague/udacity-nanodegrees#35]
Hey @mikesprague, awesome work with the resource, it's absolutely phenomenal!

Quick one though:

While perusing the new curriculum on Udacity (as of September 2018) for the FS ND, I noticed it has been hugely streamlined and reorganized and as a result, is out of sync with what is currently on this repo.

All the courses in the "new" curriculum are still freely available, though.

I have already created an "updated" version of the free resource page based on the new curriculum, and I can send over a PR if you don't mind.

![screenshot 2018-09-04 at 9 58 33 am](https://user-images.githubusercontent.com/15332525/45021410-68036200-b029-11e8-9d2b-fad21f395794.png)

---

Warm Regards.

Kizito.

**Comment by mikesprague** [comment]
Looks great @akhilome!🔥  I would definitely appreciate the pull request 🙌 

This led me to look closer at the current NDs listed on Udacity (and the PDF syllabus they're each using). I think I'll probably update all NDs in the coming weeks now that I see where to grab current syllabus. Thanks for the inspiration to give this repo some attention too!

**Comment by akhilome** [comment]
Awesome, @mikesprague! 💪

I'll get to work on the PR ASAP.

I could offer some help in updating the entire repo, too. 😀

Tell you what, after pushing an update for the full stack curriculum, I'd create a new branch off master for each curriculum I'd be working on, and opening a PR to let you know.

Cool? 😎
