### ISSUE TITLE
Add NLP Nanodegree

### ISSUE THREAD

**Issue by navidalvee** [mikesprague/udacity-nanodegrees#41]
I love this post but currently working with Natural language processing 
would love/like to see what courses you add 

thank you

**Comment by mikesprague** [comment]
Thanks for opening this issue. As mentioned in the readme for this project, if the content is not available publicly on the Udacity website then I do not have access to it (I am not an Udactiy or a Google employee). Closing for now. If you notice the content available at any point, feel free to open an issue linking to it and/or creating a pull request with the updates. Thanks!
