### ISSUE TITLE
Update Data-Engineer course

### ISSUE THREAD

**Issue by adithya-balaji** [mikesprague/udacity-nanodegrees#44]
https://www.udacity.com/course/data-engineer-nanodegree--nd027

**Comment by mikesprague** [comment]
There is no available syllabus with the exact courses listed. If you can find one, please reopen this issue and include it.

From this project's [readme](https://github.com/mikesprague/udacity-nanodegrees#why-are-only-some-of-the-nanodegrees-listed-here):

_All of the Nanodegrees programs listed here meet the following criteria:_

- _Nanodegree lists syllabus on it's public-facing (non-logged in) page_
- _Links to each course in the syllabus are available on the public-facing Nanodegree page_
- _Individual courses are available to take for free via their public facing course page_
