### ISSUE TITLE
C++ Nanodegree

### ISSUE THREAD

**Issue by moadmmh** [mikesprague/udacity-nanodegrees#45]
Can you please add the C++ nanodegree courses if possibly found .

**Comment by aviral19** [comment]
https://classroom.udacity.com/courses/ud210

This introductory course should be more than enough to cover C++.
There's no point of pursuing a nanodegree in a programming language.

**Comment by aviral19** [comment]
As such, the nanodegree hasn't even launched yet.

**Comment by moadmmh** [comment]
oh sorry then well i was just wondering on the projects ideas that they are willing to offer they seem interesting

**Comment by mikesprague** [comment]
Thanks @aviral19 👏 for answering before I could. 

And sorry @moadmmh - as mentioned in the README for this repo:
- I have NO affiliation with Udacity or Google (and therefore no access to info you do not have)
- As such, there's a reason only some are listed here (https://github.com/mikesprague/udacity-nanodegrees#why-are-only-some-of-the-nanodegrees-listed-here)

Glad you have found this project useful, and my apologies we can't provide that content for you.

**Comment by Bit145** [comment]
The C++ Nanodegree Program has launched now -
https://www.udacity.com/course/c-plus-plus-nanodegree--nd213

**Comment by aryanrawlani28** [comment]
> The C++ Nanodegree Program has launched now -
> https://www.udacity.com/course/c-plus-plus-nanodegree--nd213

Yes.. previously I saw that many course resources could be learned through for free, but I can't seem to find anything related to this one. Do you know anything about it?
