### ISSUE TITLE
Udacity courses

### ISSUE THREAD

**Issue by Jaiyashanmol** [mikesprague/udacity-nanodegrees#59]

**Comment by mikesprague** [comment]
You didn't include any information in your issue.

**Comment by Jaiyashanmol** [comment]
Sorry but I don't have much idea about how to use github

**Comment by mikesprague** [comment]
No problem at all. If you were looking to make a copy under your own namespace you can [fork](https://github.com/mikesprague/udacity-nanodegrees/fork) the repo and/or you can "star" the repo to essentially bookmark it. Hope that helps.
