### ISSUE TITLE
SWND not available now

### ISSUE THREAD

**Issue by SiqingYu** [mikesprague/udacity-nanodegrees#9]
Hi, @mikesprague 
Udacity previously closed Senior Web Developer Nanodegree program, this program is closed currently, and will come back later in a brand new form.
[Is Senior Web Developer Nanodegree discontinued?](https://discussions.udacity.com/t/is-senior-web-developer-nanodegree-discontinued/194779/20)

**Comment by mikesprague** [comment]
@SiqingYu Thanks for catching that! I verified that all courses are still available (and still free of charge) so I have left them but noted that the nanodegree is no longer listed.
